name: Node.js CI/CD
on:
    push:
      branches:
        - main
  
env:
    AZURE_WEBAPP_NAME: nodejs-web-app-service   
    AZURE_WEBAPP_PACKAGE_PATH: '.'      
    NODE_VERSION: '20'                
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .
          retention-days: 7

      - name: get info
        run: | 
          from azure.identity import ClientSecretCredential
          from azure.mgmt.web import WebSiteManagementClient
          from azure.mgmt.subscription import SubscriptionClient

          # Substitua com suas credenciais e detalhes específicos
          subscription_id = ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id = ${{ secrets.AZURE_TENANT_ID }}
          client_id = ${{ secrets.AZURE_CLIENT_ID }}
          client_secret = ${{ secrets.AZURE_CLIENT_SECRET }}

          # Autenticação usando credenciais de serviço principal
          credentials = ClientSecretCredential(
              tenant_id=tenant_id,
              client_id=client_id,
              client_secret=client_secret
          )

          # Cliente de gerenciamento de assinatura para obter detalhes da assinatura
          subscription_client = SubscriptionClient(credentials)
          subscription = next(subscription_client.subscriptions.list())

          # Cliente de gerenciamento de Web App para buscar detalhes
          web_client = WebSiteManagementClient(credentials, subscription_id)

          # Nome da Web App que você deseja buscar
          resource_group_name = 'WEB-APP-SERVICE'
          web_app_name = 'nodejs-web-app-service'

          # Buscar detalhes da Web App
          web_app = web_client.web_apps.get(resource_group_name, web_app_name)

          # Exibir o nome da Web App e o perfil do publicador
          
          print(f"Web App Name: {web_app.name}")
          print(f"Publisher Profile: {web_app.kind}")

          # Se precisar de mais detalhes, pode explorar outros atributos disponíveis em 'web_app'

  
    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
      steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
  
      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}